// Package render turns the store into the two markdown files agents read.
package render

import (
	"fmt"
	"sort"
	"strings"

	"github.com/euryopa/backecho/internal/model"
)

// MaxVerify caps the rendered verify list. The rest stay in the store.
const MaxVerify = 40

const header = "Generated by `backecho sync`. Do not edit by hand. Source is `.backecho/%s`.\nExit 0 means the command finished, not that the change was correct.\n"

// Verify renders .backecho/verify.md: verify entries, then stale, then open.
func Verify(st *model.Store) []byte {
	return render(st, model.ClassVerify, "verify", "store.json", MaxVerify)
}

// Local renders .backecho/local.md: the same row shape for local entries.
func Local(st *model.Store) []byte {
	return render(st, model.ClassLocal, "local", "local.json", 0)
}

func render(st *model.Store, class, section, source string, limit int) []byte {
	var fresh, stale []model.Entry
	for _, e := range st.Entries {
		if e.Class != class {
			continue
		}
		if e.StaleSince != nil {
			stale = append(stale, e)
		} else {
			fresh = append(fresh, e)
		}
	}
	sortEntries(fresh)
	sortEntries(stale)
	if limit > 0 && len(fresh) > limit {
		fresh = fresh[:limit]
	}

	var b strings.Builder
	b.WriteString("# backecho\n")
	fmt.Fprintf(&b, header, source)
	fmt.Fprintf(&b, "## %s\n", section)
	if len(fresh) == 0 {
		b.WriteString("_Nothing confirmed yet._\n")
	}
	for _, e := range fresh {
		row(&b, e)
	}
	if len(stale) > 0 {
		b.WriteString("## stale\n")
		for _, e := range stale {
			row(&b, e)
		}
	}

	var open []model.Open
	for _, o := range st.Open {
		if o.Class == class {
			open = append(open, o)
		}
	}
	if len(open) > 0 {
		sort.SliceStable(open, func(i, j int) bool { return open[i].TS.After(open[j].TS) })
		b.WriteString("## open\n")
		for _, o := range open {
			fmt.Fprintf(&b, "- `%s`  cwd: %s  failed: %s  via: %s", o.Command, o.Cwd, day(o.TS), o.Agent)
			if o.Hint != "" {
				fmt.Fprintf(&b, "  was: %s", o.Hint)
			}
			b.WriteByte('\n')
		}
	}
	return []byte(b.String())
}

func sortEntries(es []model.Entry) {
	sort.SliceStable(es, func(i, j int) bool {
		if es[i].OKCount != es[j].OKCount {
			return es[i].OKCount > es[j].OKCount
		}
		if !es[i].LastOK.Equal(es[j].LastOK) {
			return es[i].LastOK.After(es[j].LastOK)
		}
		return es[i].Command < es[j].Command
	})
}

func row(b *strings.Builder, e model.Entry) {
	fmt.Fprintf(b, "- `%s`\n", e.Command)
	fmt.Fprintf(b, "  cwd: %s  ok: %d", e.Cwd, e.OKCount)
	if e.FailCount > 0 {
		fmt.Fprintf(b, "  fail: %d", e.FailCount)
	}
	fmt.Fprintf(b, "  last: %s  via: %s\n", day(e.LastOK), strings.Join(via(e), ", "))
	if len(e.Env) > 0 {
		fmt.Fprintf(b, "  env: %s\n", strings.Join(e.Env, ", "))
	}
	if len(e.After) > 0 {
		fmt.Fprintf(b, "  after: %s\n", strings.Join(e.After, ", "))
	}
	if e.Was != "" {
		fmt.Fprintf(b, "  was: %s\n", e.Was)
	}
}

// via lists the agent that last confirmed the entry first, then the rest.
func via(e model.Entry) []string {
	out := []string{}
	if e.LastAgent != "" {
		out = append(out, e.LastAgent)
	}
	for _, a := range e.Agents {
		if a != e.LastAgent {
			out = append(out, a)
		}
	}
	return out
}

func day(t interface{ Format(string) string }) string { return t.Format("2006-01-02") }
