package render

import (
	"fmt"
	"strings"
	"testing"
	"time"

	"github.com/euryopa/backecho/internal/model"
)

var t0 = time.Date(2026, 10, 4, 14, 22, 0, 0, time.UTC)

func TestVerifyRow(t *testing.T) {
	fail := t0.Add(-2 * time.Minute)
	st := &model.Store{Entries: []model.Entry{{
		ID: "a1b2c3d4e5f6", Command: "npm test", Cwd: ".", Class: model.ClassVerify,
		OKCount: 12, FailCount: 2, LastOK: t0, LastFail: &fail,
		Was: "Cannot find module '@/lib/auth'", After: []string{"src/auth.ts"},
		Sessions: 4, Agents: []string{"claude", "codex"}, LastAgent: "claude",
	}}}
	got := string(Verify(st))
	want := "# backecho\n" +
		"Generated by `backecho sync`. Do not edit by hand. Source is `.backecho/store.json`.\n" +
		"Exit 0 means the command finished, not that the change was correct.\n" +
		"## verify\n" +
		"- `npm test`\n" +
		"  cwd: .  ok: 12  fail: 2  last: 2026-10-04  via: claude, codex\n" +
		"  after: src/auth.ts\n" +
		"  was: Cannot find module '@/lib/auth'\n"
	if got != want {
		t.Fatalf("got:\n%s\nwant:\n%s", got, want)
	}
}

func TestSortCapAndSections(t *testing.T) {
	st := &model.Store{}
	for i := 0; i < 45; i++ {
		st.Entries = append(st.Entries, model.Entry{Command: fmt.Sprintf("make test%02d", i), Cwd: ".", Class: model.ClassVerify, OKCount: i + 1, LastOK: t0, Agents: []string{"claude"}})
	}
	since := t0
	st.Entries = append(st.Entries,
		model.Entry{Command: "npm run old", Cwd: ".", Class: model.ClassVerify, OKCount: 99, LastOK: t0.AddDate(0, -2, 0), StaleSince: &since},
		model.Entry{Command: "PORT=:PORT npm test", Cwd: ".", Class: model.ClassLocal, OKCount: 1, LastOK: t0, Env: []string{"PORT"}},
	)
	st.Open = []model.Open{{Command: "cargo test", Cwd: ".", Class: model.ClassVerify, Agent: "codex", TS: t0, Hint: "boom"}}
	got := string(Verify(st))
	if n := strings.Count(got, "- `make test"); n != MaxVerify {
		t.Fatalf("rendered %d verify rows", n)
	}
	if !strings.Contains(got, "- `make test44`") || strings.Contains(got, "- `make test00`") {
		t.Fatal("not sorted by ok_count")
	}
	if !strings.Contains(got, "## stale\n- `npm run old`") {
		t.Fatalf("stale section missing:\n%s", got)
	}
	if !strings.Contains(got, "## open\n- `cargo test`  cwd: .  failed: 2026-10-04  via: codex  was: boom") {
		t.Fatalf("open section missing:\n%s", got)
	}
	if strings.Contains(got, "PORT") {
		t.Fatal("local entry in verify.md")
	}
	local := string(Local(st))
	if !strings.Contains(local, "## local\n- `PORT=:PORT npm test`") && !strings.Contains(local, "env: PORT") {
		t.Fatalf("local:\n%s", local)
	}
}

func TestEmptyOmitsOptionalSections(t *testing.T) {
	got := string(Verify(&model.Store{}))
	if strings.Contains(got, "## stale") || strings.Contains(got, "## open") {
		t.Fatalf("got:\n%s", got)
	}
}
